// ============================================================
// FILE: backend/services/businessDb.service.js
// PURPOSE: Gateway to the business (ERP) database.
//   - Introspects tables & schemas for AI context
//   - Executes read-only SQL queries generated by AI
//   - Provides schema info so AI can write correct SQL
// ============================================================

const bizSupabase = require('../config/businessDb');

// ── Cache schema after first fetch ──
let schemaCache = null;
let lastFetched = 0;
const SCHEMA_CACHE_TTL = 10 * 60 * 1000; // 10 min

/**
 * Load foreign key relationships from information_schema
 * Returns map: { 'tableName.columnName': { ref_table, ref_column } }
 */
const loadForeignKeyMap = async () => {
  const fkSQL = `
    SELECT
      kcu.table_name,
      kcu.column_name,
      ccu.table_name AS foreign_table_name,
      ccu.column_name AS foreign_column_name
    FROM information_schema.table_constraints AS tc
    JOIN information_schema.key_column_usage AS kcu
      ON tc.constraint_name = kcu.constraint_name
      AND tc.table_schema = kcu.table_schema
    JOIN information_schema.constraint_column_usage AS ccu
      ON ccu.constraint_name = tc.constraint_name
      AND ccu.table_schema = tc.table_schema
    WHERE tc.constraint_type = 'FOREIGN KEY'
      AND tc.table_schema = 'public'
  `;
  try {
    const rows = await executeRawSQL(fkSQL);
    if (!Array.isArray(rows)) return {};
    const map = {};
    for (const row of rows) {
      const key = `${row.table_name}.${row.column_name}`;
      map[key] = { ref_table: row.foreign_table_name, ref_column: row.foreign_column_name };
    }
    return map;
  } catch (err) {
    console.warn('[BizDB] FK introspection failed:', err.message);
    return {};
  }
};

/**
 * Execute raw SQL via RPC (the only way to query information_schema)
 * Falls back gracefully if RPC function doesn't exist yet
 */
const executeRawSQL = async (sql) => {
  // Security: only allow SELECT/WITH queries
  const trimmed = sql.trim().toUpperCase();
  if (!trimmed.startsWith('SELECT') && !trimmed.startsWith('WITH')) {
    throw new Error('Only SELECT queries are allowed');
  }

  // Block dangerous keywords
  const dangerous = /\b(INSERT|UPDATE|DELETE|DROP|ALTER|CREATE|TRUNCATE|EXEC|EXECUTE|CALL|MERGE|REPLACE)\b/i;
  if (dangerous.test(sql)) {
    throw new Error('Only read-only queries are allowed');
  }

  // Strip trailing semicolons — Supabase RPC doesn't accept them
  const cleanSql = sql.replace(/;\s*$/, '').trim();

  console.log(`[BizDB] Executing SQL (${cleanSql.split('\n')[0].slice(0, 80)}...)`);

  const { data, error } = await bizSupabase.rpc('execute_biz_query', {
    query_text: cleanSql,
  });

  if (error) {
    console.error(`[BizDB] RPC error:`, error);
    // Check if the RPC function itself is missing
    if (error.message?.includes('function') && (error.message?.includes('not found') || error.message?.includes('exists'))) {
      throw new Error('execute_biz_query RPC not found. Run database/business_supabase_functions.sql in your business Supabase SQL editor first.');
    }
    throw new Error(`DB query failed: ${error.message}`);
  }

  // execute_biz_query returns JSONB. It could be a JSON array or a single JSON object.
  if (data === null || data === undefined) return [];
  
  // If it's already an array, return as-is
  if (Array.isArray(data)) return data;
  
  // If it's a JSON object with numeric keys, convert to array
  if (typeof data === 'object') {
    const keys = Object.keys(data);
    if (keys.every(k => !isNaN(parseInt(k)))) {
      return Object.values(data);
    }
    return [data];
  }
  
  return data;
};

/**
 * Introspect all user-defined tables in the business DB
 * Returns [{ table_name, table_type, columns: [{ column_name, data_type, is_nullable, max_length }] }]
 */
const getTableSchemas = async (forceRefresh = false) => {
  const now = Date.now();
  if (!forceRefresh && schemaCache && (now - lastFetched) < SCHEMA_CACHE_TTL) {
    return schemaCache;
  }

  try {
    // Try the dedicated RPC function first
    const { data, error } = await bizSupabase.rpc('get_business_tables');
    
    if (!error && data) {
      // Parse JSONB result — could be array or object
      let tables = data;
      if (typeof tables === 'string') tables = JSON.parse(tables);
      if (!Array.isArray(tables) && typeof tables === 'object') {
        tables = Object.values(tables);
      }
      
      schemaCache = Array.isArray(tables) ? tables : [];

      // Annotate columns with FK references
      const fkMap = await loadForeignKeyMap();
      for (const t of schemaCache) {
        if (Array.isArray(t.columns)) {
          for (const c of t.columns) {
            const fk = fkMap[`${t.table_name}.${c.column_name}`];
            if (fk) c.foreign_key = fk;
          }
        }
      }

      lastFetched = now;
      return schemaCache;
    }
  } catch (e) {
    console.warn('[BizDB] get_business_tables RPC failed:', e.message);
  }

  // Fallback: use execute_biz_query with raw SQL
  try {
    const tablesSQL = `
      SELECT table_name, table_type 
      FROM information_schema.tables 
      WHERE table_schema = 'public' 
        AND table_type IN ('BASE TABLE', 'VIEW')
        AND table_name NOT LIKE '\\_%'
      ORDER BY table_name
    `;
    const tables = await executeRawSQL(tablesSQL);
    if (!Array.isArray(tables)) {
      schemaCache = [];
      lastFetched = now;
      return [];
    }

    const schemas = [];
    for (const table of tables) {
      const colsSQL = `
        SELECT column_name, data_type, is_nullable, character_maximum_length
        FROM information_schema.columns
        WHERE table_schema = 'public'
          AND table_name = '${table.table_name?.replace(/'/g, "''")}'
        ORDER BY ordinal_position
      `;
      try {
        const columns = await executeRawSQL(colsSQL);
        schemas.push({
          table_name: table.table_name,
          table_type: table.table_type,
          columns: Array.isArray(columns) ? columns.map(c => ({
            column_name: c.column_name,
            data_type: c.data_type,
            is_nullable: c.is_nullable,
            max_length: c.character_maximum_length,
          })) : [],
        });
      } catch {
        // Skip tables that fail
      }
    }

    // Annotate columns with FK references
    const fkMap = await loadForeignKeyMap();
    for (const t of schemas) {
      if (Array.isArray(t.columns)) {
        for (const c of t.columns) {
          const fk = fkMap[`${t.table_name}.${c.column_name}`];
          if (fk) c.foreign_key = fk;
        }
      }
    }

    schemaCache = schemas;
    lastFetched = now;
    return schemas;
  } catch (err) {
    console.error('[BizDB] Schema introspection failed:', err.message);
    schemaCache = [];
    lastFetched = now;
    return [];
  }
};

/**
 * Semantic descriptions for each ERP table to help AI map questions to correct tables
 */
const TABLE_DESCRIPTIONS = {
  companies: 'Company master data — codes, names, country, currency. Use for company-level info.',
  plants: 'Manufacturing/distribution plants belonging to companies.',
  storage_locations: 'Warehouse/storage locations within plants.',
  cost_centers: 'Cost centers for expense tracking and controlling (CO module).',
  gl_accounts: 'General ledger chart of accounts (FI module).',
  vendors: 'Supplier/vendor master data.',
  customers: 'Customer master data — use for customer info, accounts.',
  journal_entries: 'FI journal entries (accounting documents) header.',
  journal_entry_items: 'Line items for each journal entry (debit/credit).',
  invoices: 'Accounts receivable/payable invoice headers.',
  invoice_items: 'Line items on invoices.',
  bank_accounts: 'Company bank accounts for payments/receipts.',
  cost_elements: 'Cost element master (CO module) — categories of costs.',
  internal_orders: 'Internal orders for short-term cost monitoring.',
  cost_center_allocation: 'Cost allocations between cost centers.',
  profit_center: 'Profit centers for profitability analysis.',
  materials: 'Material/product master data — codes, descriptions, types.',
  material_plant_data: 'Plant-specific material data (shelf life, storage).',
  material_storage_location: 'Material quantities by storage location.',
  purchase_requisitions: 'Purchase requisition (indent) headers.',
  purchase_requisition_items: 'Line items in purchase requisitions.',
  purchase_orders: 'Purchase order headers sent to vendors.',
  purchase_order_items: 'Line items in purchase orders.',
  goods_receipts: 'Goods receipt document headers.',
  goods_receipt_items: 'Line items in goods receipts.',
  stock_movements: 'All inventory movement transactions (goods issue/receipt/transfer).',
  sales_orders: 'Sales order headers from customers.',
  sales_order_items: 'Line items in sales orders.',
  delivery_orders: 'Outbound delivery document headers.',
  delivery_items: 'Line items in outbound deliveries.',
  billing_documents: 'Billing/invoice document headers to customers.',
  billing_document_items: 'Line items in billing documents.',
  bills_of_material: 'BOM headers — product structure/routing.',
  bom_items: 'Component items in each BOM.',
  work_centers: 'Production work centers / machines.',
  routings: 'Production routing headers (sequence of operations).',
  routing_operations: 'Individual operations in production routing.',
  production_orders: 'Production order headers.',
  production_order_operations: 'Operations within production orders.',
  production_confirmations: 'Production confirmation (actual labor/machine time booked).',
  employees: 'Employee master data — personal info, type, active status, employment dates.',
  positions: 'Job positions/roles in the organization.',
  employee_assignments: 'Employee-to-position assignments history.',
  salaries: 'Employee salary records (basic, allowances, deductions).',
  payroll_runs: 'Payroll processing batch headers.',
  payroll_details: 'Payroll calculation details per employee per run.',
  leave_types: 'Leave categories (sick, vacation, personal, etc.).',
  leave_requests: 'Employee leave applications and approvals.',
  contacts: 'CRM contact persons at customer/vendor companies.',
  opportunities: 'CRM sales opportunities / pipeline.',
  activities: 'CRM activities — calls, meetings, tasks, emails.',
  campaigns: 'Marketing campaign tracking.',
  supplier_scorecards: 'Vendor performance evaluation scores.',
  supplier_contracts: 'Long-term contracts/agreements with vendors.',
  supplier_quotations: 'Vendor quotations for materials/services.',
  supplier_quotation_items: 'Line items in supplier quotations.',
};

/**
 * Build a human-readable schema description for the AI system prompt
 */
const buildSchemaContext = async () => {
  const schemas = await getTableSchemas();
  if (!schemas || schemas.length === 0) {
    return '';
  }

  // Table guide: helps AI understand what each table is for
  const guideLines = schemas
    .filter(t => TABLE_DESCRIPTIONS[t.table_name])
    .map(t => `  - ${t.table_name}: ${TABLE_DESCRIPTIONS[t.table_name]}`);

  const guideBlock = guideLines.length > 0
    ? `\n\n[TABLE GUIDE — what each table contains]\n${guideLines.join('\n')}\n[END GUIDE]`
    : '';

  const lines = schemas.map(table => {
    const cols = (table.columns || [])
      .map(c => {
        let line = `  - ${c.column_name} (${c.data_type}${c.is_nullable === 'NO' ? ', NOT NULL' : ''}${c.max_length ? `, max ${c.max_length}` : ''}`;
        if (c.foreign_key) {
          line += `) → REFERENCES ${c.foreign_key.ref_table}(${c.foreign_key.ref_column})`;
        } else {
          line += ')';
        }
        return line;
      })
      .join('\n');
    return `TABLE: ${table.table_name}\n${cols}`;
  });

  return `[BUSINESS DATABASE SCHEMA]\n${lines.join('\n\n')}\n[END SCHEMA]${guideBlock}\n\n` +
    `You have read-only access to this database. To query it, respond with:\n` +
    `[QUERY_DB]\n<SQL_QUERY>\n[/QUERY_DB]\n\n` +
    `Rules:\n` +
    `- Only SELECT queries allowed (read-only)\n` +
    `- Use table names exactly as shown above\n` +
    `- Use column names exactly as shown above\n` +
    `- Limit results with LIMIT when appropriate\n` +
    `- Do NOT use transactions, DDL, DML, or EXPLAIN\n` +
    `- Do NOT use semicolons (;) at the end of SQL queries\n` +
    `- For date queries, use ISO format (YYYY-MM-DD)\n` +
    `- Use the TABLE GUIDE above to pick the RIGHT table for the user's question`;
};

/**
 * Build a minimal schema context — TABLE GUIDE only, no full column listing.
 * AI uses GET_SCHEMA tool to fetch columns on-demand for only the tables it needs.
 */
const buildMinimalSchemaContext = async () => {
  const schemas = await getTableSchemas();
  if (!schemas || schemas.length === 0) {
    return '';
  }

  const guideLines = schemas
    .filter(t => TABLE_DESCRIPTIONS[t.table_name])
    .map(t => `  - ${t.table_name}: ${TABLE_DESCRIPTIONS[t.table_name]}`);

  const guideBlock = guideLines.length > 0
    ? `\n\n[TABLE GUIDE — what each table contains]\n${guideLines.join('\n')}\n[END GUIDE]`
    : '';

  // Build relationships section from foreign keys
  const relLines = [];
  for (const table of schemas) {
    if (!Array.isArray(table.columns)) continue;
    for (const col of table.columns) {
      if (col.foreign_key) {
        relLines.push(`  - ${table.table_name}.${col.column_name} \u2192 ${col.foreign_key.ref_table}(${col.foreign_key.ref_column})`);
      }
    }
  }

  const relBlock = relLines.length > 0
    ? `\n\n[TABLE RELATIONSHIPS — foreign keys for JOIN queries]\n${relLines.join('\n')}\n[END RELATIONSHIPS]`
    : '';

  return `[BUSINESS DATABASE — TABLES OVERVIEW]${guideBlock}${relBlock}\n\n` +
    `You have read-only access to this database. To query it:\n` +
    `1. First get column schema: [GET_SCHEMA:table1, table2, ...]\n` +
    `2. Then query: [QUERY_DB]\n   <SQL_QUERY>\n   [/QUERY_DB]\n\n` +
    `Rules:\n` +
    `- When user mentions a business entity (e.g., Purchase Order, Vendor, Sales Order), call GET_SCHEMA with ONLY its directly related tables (e.g., [GET_SCHEMA:purchase_orders, companies, vendors]) — do NOT request all tables at once; use TABLE GUIDE + RELATIONSHIPS to identify relevant tables\n` +
    `- Only SELECT queries allowed (read-only)\n` +
    `- Use table names exactly as shown in TABLE GUIDE\n` +
    `- Use column names exactly as returned by GET_SCHEMA\n` +
    `- Limit results with LIMIT when appropriate\n` +
    `- Do NOT use transactions, DDL, DML, or EXPLAIN\n` +
    `- Do NOT use semicolons (;) at the end of SQL queries\n` +
    `- For date queries, use ISO format (YYYY-MM-DD)\n` +
    `- Use the TABLE GUIDE above to pick the RIGHT table for the user's question`;
};

/**
 * Get column schema for one or more specific tables
 * @param {string|string[]} tableNames - Table name or array of table names
 * @returns {string} Formatted schema text for the requested tables
 */
const getTableSchema = async (tableNames) => {
  const schemas = await getTableSchemas();
  const names = Array.isArray(tableNames) ? tableNames : [tableNames];

  const filtered = schemas.filter(t => names.includes(t.table_name));
  if (filtered.length === 0) {
    return `[GET_SCHEMA RESULT]\nNo tables found matching: ${names.join(', ')}\n[END RESULT]`;
  }

  const lines = filtered.map(table => {
    const cols = (table.columns || [])
      .map(c => {
        let line = `  - ${c.column_name} (${c.data_type}${c.is_nullable === 'NO' ? ', NOT NULL' : ''}${c.max_length ? `, max ${c.max_length}` : ''}`;
        if (c.foreign_key) {
          line += `) → REFERENCES ${c.foreign_key.ref_table}(${c.foreign_key.ref_column})`;
        } else {
          line += ')';
        }
        return line;
      })
      .join('\n');
    return `TABLE: ${table.table_name}\n${cols}`;
  });

  return `[SCHEMA FOR: ${names.join(', ')}]\n${lines.join('\n\n')}\n[END SCHEMA]`;
};

/**
 * Execute a read-only SQL query against the business DB
 * @param {string} sql - SELECT query to execute
 * @returns {Array} rows
 */
const executeQuery = async (sql) => {
  return await executeRawSQL(sql);
};

/**
 * Execute a query with fallback
 */
const queryBusinessDB = async (sql) => {
  try {
    return await executeQuery(sql);
  } catch (err) {
    console.error('[BizDB] Query error:', err.message);
    throw err;
  }
};

/**
 * Get row count estimate for a table
 */
const getTableRowCount = async (tableName) => {
  try {
    const result = await executeRawSQL(
      `SELECT COUNT(*) as count FROM "${tableName.replace(/"/g, '""')}"`
    );
    if (Array.isArray(result) && result.length > 0) {
      return parseInt(result[0].count, 10) || 0;
    }
    // Handle case where result is a single object
    if (result && result.count !== undefined) {
      return parseInt(result.count, 10) || 0;
    }
    return 0;
  } catch {
    return null;
  }
};

/**
 * Check if business DB is connected and has execute_biz_query available
 */
const isConnected = async () => {
  try {
    await executeRawSQL('SELECT 1 as ok');
    return true;
  } catch {
    return false;
  }
};

// ── Lazy singleton: initialised once, shared across consumers ──
let _bizDbConnected = null;
let _bizDbSchemaText = '';
let _bizDbMinimalSchemaText = '';
let _initPromise = null;

/**
 * Initialise the business DB connection state (idempotent — safe to call multiple times)
 * @returns {{ connected: boolean, schemaText: string, minimalSchemaText: string }}
 */
const initBusinessDB = async () => {
  if (_bizDbConnected !== null) {
    return { connected: _bizDbConnected, schemaText: _bizDbSchemaText, minimalSchemaText: _bizDbMinimalSchemaText };
  }
  if (_initPromise) {
    return _initPromise;
  }
  _initPromise = (async () => {
    try {
      _bizDbConnected = await isConnected();
      if (_bizDbConnected) {
        _bizDbSchemaText = await buildSchemaContext();
        _bizDbMinimalSchemaText = await buildMinimalSchemaContext();
        console.log('[BizDB] ✅ Business database connected');
      } else {
        console.log('[BizDB] ⚠️ Business database not configured');
      }
    } catch (err) {
      _bizDbConnected = false;
      console.warn('[BizDB] ❌ Failed to connect:', err.message);
    }
    return { connected: _bizDbConnected, schemaText: _bizDbSchemaText, minimalSchemaText: _bizDbMinimalSchemaText };
  })();
  return _initPromise;
};

module.exports = {
  getTableSchemas,
  buildSchemaContext,
  buildMinimalSchemaContext,
  getTableSchema,
  queryBusinessDB,
  executeQuery,
  executeRawSQL,
  getTableRowCount,
  isConnected,
  initBusinessDB,
};
