// ============================================================
// FILE: backend/services/businessDb.service.js
// PURPOSE: Gateway to the business (ERP) database.
//   - Introspects tables & schemas for AI context
//   - Executes read-only SQL queries generated by AI
//   - Provides schema info so AI can write correct SQL
// ============================================================

const bizSupabase = require('../config/businessDb');

// ── Cache schema after first fetch ──
let schemaCache = null;
let lastFetched = 0;
const SCHEMA_CACHE_TTL = 10 * 60 * 1000; // 10 min

/**
 * Execute raw SQL via RPC (the only way to query information_schema)
 * Falls back gracefully if RPC function doesn't exist yet
 */
const executeRawSQL = async (sql) => {
  // Security: only allow SELECT/WITH queries
  const trimmed = sql.trim().toUpperCase();
  if (!trimmed.startsWith('SELECT') && !trimmed.startsWith('WITH')) {
    throw new Error('Only SELECT queries are allowed');
  }

  // Block dangerous keywords
  const dangerous = /\b(INSERT|UPDATE|DELETE|DROP|ALTER|CREATE|TRUNCATE|EXEC|EXECUTE|CALL|MERGE|REPLACE)\b/i;
  if (dangerous.test(sql)) {
    throw new Error('Only read-only queries are allowed');
  }

  console.log(`[BizDB] Executing SQL (${sql.trim().split('\n')[0].slice(0, 80)}...)`);

  const { data, error } = await bizSupabase.rpc('execute_biz_query', {
    query_text: sql,
  });

  if (error) {
    console.error(`[BizDB] RPC error:`, error);
    // Check if the RPC function itself is missing
    if (error.message?.includes('function') && (error.message?.includes('not found') || error.message?.includes('exists'))) {
      throw new Error('execute_biz_query RPC not found. Run database/business_supabase_functions.sql in your business Supabase SQL editor first.');
    }
    throw new Error(`DB query failed: ${error.message}`);
  }

  // execute_biz_query returns JSONB. It could be a JSON array or a single JSON object.
  if (data === null || data === undefined) return [];
  
  // If it's already an array, return as-is
  if (Array.isArray(data)) return data;
  
  // If it's a JSON object with numeric keys, convert to array
  if (typeof data === 'object') {
    const keys = Object.keys(data);
    if (keys.every(k => !isNaN(parseInt(k)))) {
      return Object.values(data);
    }
    return [data];
  }
  
  return data;
};

/**
 * Introspect all user-defined tables in the business DB
 * Returns [{ table_name, table_type, columns: [{ column_name, data_type, is_nullable, max_length }] }]
 */
const getTableSchemas = async (forceRefresh = false) => {
  const now = Date.now();
  if (!forceRefresh && schemaCache && (now - lastFetched) < SCHEMA_CACHE_TTL) {
    return schemaCache;
  }

  try {
    // Try the dedicated RPC function first
    const { data, error } = await bizSupabase.rpc('get_business_tables');
    
    if (!error && data) {
      // Parse JSONB result — could be array or object
      let tables = data;
      if (typeof tables === 'string') tables = JSON.parse(tables);
      if (!Array.isArray(tables) && typeof tables === 'object') {
        tables = Object.values(tables);
      }
      
      schemaCache = Array.isArray(tables) ? tables : [];
      lastFetched = now;
      return schemaCache;
    }
  } catch (e) {
    console.warn('[BizDB] get_business_tables RPC failed:', e.message);
  }

  // Fallback: use execute_biz_query with raw SQL
  try {
    const tablesSQL = `
      SELECT table_name, table_type 
      FROM information_schema.tables 
      WHERE table_schema = 'public' 
        AND table_type IN ('BASE TABLE', 'VIEW')
        AND table_name NOT LIKE '\\_%'
      ORDER BY table_name
    `;
    const tables = await executeRawSQL(tablesSQL);
    if (!Array.isArray(tables)) {
      schemaCache = [];
      lastFetched = now;
      return [];
    }

    const schemas = [];
    for (const table of tables) {
      const colsSQL = `
        SELECT column_name, data_type, is_nullable, character_maximum_length
        FROM information_schema.columns
        WHERE table_schema = 'public'
          AND table_name = '${table.table_name?.replace(/'/g, "''")}'
        ORDER BY ordinal_position
      `;
      try {
        const columns = await executeRawSQL(colsSQL);
        schemas.push({
          table_name: table.table_name,
          table_type: table.table_type,
          columns: Array.isArray(columns) ? columns.map(c => ({
            column_name: c.column_name,
            data_type: c.data_type,
            is_nullable: c.is_nullable,
            max_length: c.character_maximum_length,
          })) : [],
        });
      } catch {
        // Skip tables that fail
      }
    }

    schemaCache = schemas;
    lastFetched = now;
    return schemas;
  } catch (err) {
    console.error('[BizDB] Schema introspection failed:', err.message);
    schemaCache = [];
    lastFetched = now;
    return [];
  }
};

/**
 * Build a human-readable schema description for the AI system prompt
 */
const buildSchemaContext = async () => {
  const schemas = await getTableSchemas();
  if (!schemas || schemas.length === 0) {
    return '';
  }

  const lines = schemas.map(table => {
    const cols = (table.columns || [])
      .map(c => `  - ${c.column_name} (${c.data_type}${c.is_nullable === 'NO' ? ', NOT NULL' : ''}${c.max_length ? `, max ${c.max_length}` : ''})`)
      .join('\n');
    return `TABLE: ${table.table_name}\n${cols}`;
  });

  return `[BUSINESS DATABASE SCHEMA]\n${lines.join('\n\n')}\n[END SCHEMA]\n\n` +
    `You have read-only access to this database. To query it, respond with:\n` +
    `[QUERY_DB]\n<SQL_QUERY>\n[/QUERY_DB]\n\n` +
    `Rules:\n` +
    `- Only SELECT queries allowed (read-only)\n` +
    `- Use table names exactly as shown above\n` +
    `- Use column names exactly as shown above\n` +
    `- Limit results with LIMIT when appropriate\n` +
    `- Do NOT use transactions, DDL, DML, or EXPLAIN\n` +
    `- For date queries, use ISO format (YYYY-MM-DD)`;
};

/**
 * Execute a read-only SQL query against the business DB
 * @param {string} sql - SELECT query to execute
 * @returns {Array} rows
 */
const executeQuery = async (sql) => {
  return await executeRawSQL(sql);
};

/**
 * Execute a query with fallback
 */
const queryBusinessDB = async (sql) => {
  try {
    return await executeQuery(sql);
  } catch (err) {
    console.error('[BizDB] Query error:', err.message);
    throw err;
  }
};

/**
 * Get row count estimate for a table
 */
const getTableRowCount = async (tableName) => {
  try {
    const result = await executeRawSQL(
      `SELECT COUNT(*) as count FROM "${tableName.replace(/"/g, '""')}"`
    );
    if (Array.isArray(result) && result.length > 0) {
      return parseInt(result[0].count, 10) || 0;
    }
    // Handle case where result is a single object
    if (result && result.count !== undefined) {
      return parseInt(result.count, 10) || 0;
    }
    return 0;
  } catch {
    return null;
  }
};

/**
 * Check if business DB is connected and has execute_biz_query available
 */
const isConnected = async () => {
  try {
    await executeRawSQL('SELECT 1 as ok');
    return true;
  } catch {
    return false;
  }
};

module.exports = {
  getTableSchemas,
  buildSchemaContext,
  queryBusinessDB,
  executeQuery,
  executeRawSQL,
  getTableRowCount,
  isConnected,
};
