// FILE: backend/services/pdfGeneration.service.js
// PURPOSE: Generate PDF files using pdfkit
const PDFDocument = require('pdfkit');
const { saveGeneratedBinaryFile } = require('./fileUpload.service');

/**
 * Generate a PDF from structured sections
 * @param {string} title
 * @param {Array<{heading:string, content:string}>} sections
 * @param {string} userId
 * @param {string|null} topicId
 */
const generatePDF = async (title, sections, userId, topicId) => {
  console.log(`[PDFGen] Generating PDF: "${title}" with ${sections.length} sections`);

  return new Promise((resolve, reject) => {
    const chunks = [];
    const doc = new PDFDocument({ size: 'A4', margin: 50 });

    doc.on('data', (chunk) => chunks.push(chunk));
    doc.on('end', async () => {
      try {
        const buffer = Buffer.concat(chunks);

        const safeName = (title || 'document')
          .slice(0, 40)
          .replace(/[^a-z0-9\s]/gi, '')
          .trim()
          .replace(/\s+/g, '_')
          .toLowerCase() || 'document';

        const fileName = `${safeName}_${Date.now()}.pdf`;
        const textContent = `PDF Document: ${title}\nSections: ${sections.length}\n${sections.map((s, i) => `  ${i + 1}. ${s.heading}`).join('\n')}`;

        const result = await saveGeneratedBinaryFile(userId, topicId, fileName, textContent, 'pdf', buffer);
        if (!result) return reject(new Error('Failed to save generated PDF to database'));

        console.log(`[PDFGen] Saved as ${result.file_name} (id: ${result.file_id})`);
        resolve(result);
      } catch (err) {
        reject(err);
      }
    });

    // Title
    doc.fontSize(24).font('Helvetica-Bold').text(title || 'Document', { align: 'center' });
    doc.moveDown(1.5);

    // Sections
    for (const section of sections) {
      if (section.heading) {
        doc.fontSize(16).font('Helvetica-Bold').text(section.heading);
        doc.moveDown(0.5);
      }
      if (section.content) {
        doc.fontSize(11).font('Helvetica').text(section.content, { lineGap: 4 });
        doc.moveDown(1);
      }
    }

    // Footer
    doc.moveDown(1);
    doc.fontSize(8).font('Helvetica').fillColor('#999')
      .text(`Generated by Multi-AI Chat | ${new Date().toISOString().split('T')[0]}`, { align: 'center' });

    doc.end();
  });
};

module.exports = { generatePDF };
