// FILE: backend/services/wordGeneration.service.js
// PURPOSE: Generate Word (.docx) files using docx library
const { Document, Packer, Paragraph, TextRun, HeadingLevel } = require('docx');
const { saveGeneratedBinaryFile } = require('./fileUpload.service');

/**
 * Generate a Word document from structured sections
 * @param {string} title
 * @param {Array<{heading:string, content:string}>} sections
 * @param {string} userId
 * @param {string|null} topicId
 */
const generateDocx = async (title, sections, userId, topicId) => {
  console.log(`[DocxGen] Generating DOCX: "${title}" with ${sections.length} sections`);

  const children = [];

  // Title
  children.push(
    new Paragraph({
      text: title || 'Document',
      heading: HeadingLevel.TITLE,
      alignment: 'center',
      spacing: { after: 400 },
    })
  );

  // Sections
  for (const section of sections) {
    if (section.heading) {
      children.push(
        new Paragraph({
          text: section.heading,
          heading: HeadingLevel.HEADING_1,
          spacing: { before: 300, after: 150 },
        })
      );
    }
    if (section.content) {
      // Split content into paragraphs
      const paragraphs = section.content.split('\n').filter((p) => p.trim());
      for (const para of paragraphs) {
        children.push(
          new Paragraph({
            children: [new TextRun({ text: para, size: 22 })],
            spacing: { after: 120 },
          })
        );
      }
    }
  }

  // Footer
  children.push(
    new Paragraph({
      children: [
        new TextRun({
          text: `\nGenerated by Multi-AI Chat | ${new Date().toISOString().split('T')[0]}`,
          size: 16,
          color: '999999',
          italics: true,
        }),
      ],
      alignment: 'center',
      spacing: { before: 600 },
    })
  );

  const doc = new Document({
    sections: [{ children }],
  });

  const buffer = await Packer.toBuffer(doc);

  const safeName = (title || 'document')
    .slice(0, 40)
    .replace(/[^a-z0-9\s]/gi, '')
    .trim()
    .replace(/\s+/g, '_')
    .toLowerCase() || 'document';

  const fileName = `${safeName}_${Date.now()}.docx`;
  const textContent = `Word Document: ${title}\nSections: ${sections.length}\n${sections.map((s, i) => `  ${i + 1}. ${s.heading}`).join('\n')}`;

  const result = await saveGeneratedBinaryFile(userId, topicId, fileName, textContent, 'docx', buffer);
  if (!result) throw new Error('Failed to save generated DOCX to database');

  console.log(`[DocxGen] Saved as ${result.file_name} (id: ${result.file_id})`);
  return result;
};

module.exports = { generateDocx };
